spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587
    username: anh435109@gmail.com
    password: nmau jqmf tydh gcff
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
